project:
  type: website
  output-dir: docs

website:
  title: "template4"
  navbar:
    left:
      - href: home.qmd
        text: HOME
      - href: about.qmd
        text: ABOUT
      - href: ingridients.qmd
        text: INGREDIENTS
      - href: products.qmd
        text: PRODUCTS
      - href: contact.qmd
        text: CONTACT

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



